#!/usr/bin/env php
<?php

foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        define('TESTBUCKET_COMPOSER_INSTALL', $file);
        break;
    }
}
unset($file);

if (!defined('TESTBUCKET_COMPOSER_INSTALL')) {
    fwrite(STDERR, 'Setup error');
    die(1);
}

require TESTBUCKET_COMPOSER_INSTALL;

use Symfony\Component\Console\Application;
use TestBucket\Command\Bucket\GenerateCommand;
use TestBucket\Command\Bucket\CleanUpCommand;

/*
use Doctrine\ORM\Tools\Setup;
use Doctrine\ORM\EntityManager;

$isDevMode = true;
$config = Setup::createXMLMetadataConfiguration(array(__DIR__."/config/xml"), $isDevMode);

$entityManager = EntityManager::create([
    'driver' => 'pdo_sqlite',
    'path' => getenv('TESTBUCKET_DIR'),
], $config);
*/

$application = new Application();
$application->add(new GenerateCommand());
$application->add(new CleanUpCommand());
$application->run();
