name: Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          make test
